image: docker:latest
services:
  - docker:dind

stages:
  - test
  - deploy


step-test-dev:
  stage: test
  before_script:
    - export DYNAMIC_ENV_VAR=DEV
  only:
    - master
  tags:
    - master
  script:
    - echo running tests in $DYNAMIC_ENV_VAR

step-deploy-dev:
  stage: test
  before_script:
    - export DYNAMIC_ENV_VAR=DEV
  only:
    - master
  tags:
    - master
  script:
    - echo running DEPLOY in $DYNAMIC_ENV_VAR
    - export
    - env
    - sudo ansible-playbook UpdateImages.yml
  when: manual

step-Copy-File-R:
  stage: test
  before_script:
    - export DYNAMIC_ENV_VAR=DEV
  only:
    - master
  when: manual

  tags:
    - master
  script:
    - echo running DEPLOY in $DYNAMIC_ENV_VAR
    - export
    - env
    - echo running CI_INPUT_ZONEENV in $CI_INPUT_ZONEENV
    - sudo ansible-playbook playbooks/CopyFileRlocal.yml --extra-vars "ENV=$CI_INPUT_ZONEENV CI_PROJECT_DIR=$CI_PROJECT_DIR"