---
- hosts: CM-Tools-Server
  vars_files:
  - env_variables

  tasks:
############################################################
# PAM.D RSTUDIO
############################################################
    - name: Copy file /cm/images/{{ images_name }}/src/etc/pam.d/rstudio - Copy file -
      copy:
         src: "{{ CI_PROJECT_DIR }}/src/etc/pam.d/rstudio"
         dest: /cm/images/{{ images_name }}/etc/pam.d/rstudio
         backup: no
         owner: root
         group: root
         mode: '0644' 