---
- hosts: R-BATCH-{{ ENV }}
  vars_files:
  - env_variables

  tasks:
    - name: Install R - WISE - 3.3.3 - Copy file /R/etc
      copy:
        src: "{{ CI_PROJECT_DIR }}/src/opt/Ropen/R/etc"
        dest: /usr/lib64/microsoft-r/3.3/lib64/R/etc
        backup: yes
        owner: root
        group: root
        mode: '0644'

    - name: Install R - WISE - 3.4.0 - Copy file /R/etc
      copy:
        src: "{{ CI_PROJECT_DIR }}/src/opt/Ropen/R/etc"
        dest: /usr/lib64/microsoft-r/3.4/lib64/R/etc
        backup: yes
        owner: root
        group: root
        mode: '0644'

    - name: Copy file /R/etc - Install R - WISE - 3.4.1
      copy:
         src: "{{ CI_PROJECT_DIR }}/src/opt/Ropen/R/etc"
         dest: /opt/microsoft/ropen/3.4.1/lib64/R/etc
         backup: yes
         owner: root
         group: root
         mode: '0644'

    - name: Copy file /R/etc - Install R - WISE - 3.4.2
      copy:
         src: "{{ CI_PROJECT_DIR }}/src/opt/Ropen/R/etc"
         dest: /opt/microsoft/ropen/3.4.2/lib64/R/etc
         backup: yes
         owner: root
         group: root
         mode: '0644'

    - name: Copy file /R/etc - Install R - WISE - 3.4.3
      copy:
         src: "{{ CI_PROJECT_DIR }}/src/opt/Ropen/R/etc"
         dest: /opt/microsoft/ropen/3.4.3/lib64/R/etc
         backup: yes
         owner: root
         group: root
         mode: '0644'


    - name: Copy file /R/etc - Install R - WISE - 3.5.1
      copy:
         src: "{{ CI_PROJECT_DIR }}/src/opt/Ropen/R/etc"
         dest: /opt/microsoft/ropen/3.5.1/lib64/R/etc
         backup: yes
         owner: root
         group: root
         mode: '0644'

    - name: Copy file /R/etc - Install R - WISE - 3.5.3
      copy:
         #src: /cm/shared/apps/UpdateImages/Scenario/R/{{TYPE_WISE_MODULE}}/src/opt/Ropen/R/etc
         src: "{{ CI_PROJECT_DIR }}/src/opt/Ropen/R/etc"
         dest: /opt/microsoft/ropen/3.5.3/lib64/R/etc
         backup: yes
         owner: root
         group: root
         mode: '0644'
