---
- hosts: CM-Tools-Server
  vars_files:
  - env_variables

  tasks:

      - name: Creates Files - /cm/images/{{ images_name }}/src/etc/yum/vars/releasever
        copy:
          src: "{{ CI_PROJECT_DIR }}/src/etc/yum/vars/releasever"
          dest: /cm/images/{{ images_name }}/etc/yum/vars/releasever
          backup: no
          owner: root
          group: root
          mode: '0755'