---
- hosts: CM-Tools-Server 
  vars_files:
  - env_variables

  tasks:
    - name: Remove Package Docker
      vars:
        packages_docker:
          - docker-common-1.13.1-108.git4ef4b30.el7.x86_64
          - docker-1.13.1-108.git4ef4b30.el7.x86_64
          - docker-rhel-push-plugin-1.13.1-108.git4ef4b30.el7.x86_64
          - docker-client-1.13.1-108.git4ef4b30.el7.x86_64
      yum:
        name: "{{ packages_docker }}"
        installroot: /cm/images/{{ images_name }}/
        state: removed



