---
- hosts: CM-Tools-Server 
  vars_files:
  - env_variables

  tasks:
    - name: "Chrrot on the images"
      command: " chroot /cm/images/{{ images_name }}"
      
    - name: Remove Package Docker
      vars:
        packages_docker:
          - docker
          - docker-client 
          - docker-client-latest 
          - docker-common 
          - docker-latest 
          - docker-latest-logrotate 
          - docker-logrotate 
          - docker-engine

      yum:
        name: "{{ packages_docker }}"
        #installroot: /cm/images/{{ images_name }}/
        state: removed




