---
- hosts: CM-Tools-Server 
  vars_files:
  - env_variables

  tasks:

    - name: Remove Package rstudio-server 
      yum:
        name: rstudio-server 
        installroot: /cm/images/{{ images_name }}/
        state: removed
