---
- hosts: CM-Tools-Server 
  vars_files:
  - env_variables

  tasks:


    - name: "Chrrot on the images"
      command: " chroot /cm/images/{{ images_name }}"


    - name: Remove Certtificat 
      yum:
        name: katello-ca-consumer
        state: removed

    - name: "Install new Certificat"
      yum:
        name: "{{ katello-url }}"
        state: present
  

    - name: "Register the images"
      command: "{{ register-cmd }}"




