---
- hosts: CM-Tools-Server 
  vars_files:
  - env_variables

  tasks:


    - name: "Chrrot on the images"
      command: " chroot /cm/images/{{ images_name }}"


    - name: "Remove Certtificat" 
      yum:
        name: katello-ca-consumer-*
        state: removed

    - name: "Install new Certificat"
      yum:
        name: "{{ katelloUrl }}"
        state: present
        
    
    - name: "Valiadated inside chroot"
      command: "ls -alrt /cm"
      register: InsideChroot
    
   
    - name: "Register the images"
      command: "{{ registerCmd }}"




