---
- hosts: CM-Tools-Server 
  vars_files:
  - env_variables

  tasks:
    - name: "Chrrot on the images"
      command: " chroot /cm/images/{{ images_name }}"

    - name: Remove Certtificat 
      yum:
        name: katello-ca-consumer-*
        state: removed

    - name: "Install new Certificat"
      yum:
        name: "{{ katelloUrl }}"
        state: present
  

    - name: "Register the images"
      command: "{{ registerCmd }}"

    - name: " yum clean all"
      command: " yum clean all"

    - name: "subscription-manager status"
      command: "subscription-manager status"
      register: subscriptionStatus

    - debug: msg="subscriptionStatus -> {{ subscriptionStatus.stdout }}"
    - debug: msg="Image path-> /cm/images/{{ images_name }}"

    - name: "Valiadated inside chroot"
      command: "ls -alrt /cm"
      register: InsideChroot
    
    - debug: msg="InsideChroot-> {{ InsideChroot }}"

    - name: Download jenkins.repo
      get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins Key
      rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present


    #- name: "Install Repo jenkins"
    #   command: "curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.rep"

     #- name: " add keys - jenkins-ci.org.key"
       #command: "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"

     #- name: Install package for jenkins
       #vars:
         #packages:
           #- jenkins
       #yum:
         #name: "{{ packages }}"
