---
- hosts: CM-Tools-Server 
  vars_files:
  - env_variables

  tasks:
    - name: Install package for postgresql
      vars:
        packages:
          - postgresql-devel.x86_64
          - poppler.x86_64 
      yum:
        name: "{{ packages }}"
        #disablerepo: "epel,ol7_latest"
        installroot: /cm/images/{{ images_name }}/

    - name: Install package for magick
      vars:
        packages:
          - ImageMagick-c++.x86_64
      yum:
        name: "{{ packages }}"
        #disablerepo: "epel,ol7_latest"
        installroot: /cm/images/{{ images_name }}/


