---
- hosts: CM-Tools-Server 
  vars_files:
  - env_variables

  tasks:

    - name: Install R - WISE - 3.3.3
      vars:
        packages3_3_3:
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.3.3/microsoft-r-open/rpm/microsoft-r-open-mro-3.3.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.3.3/microsoft-r-open/rpm/microsoft-r-open-foreachiterators-3.3.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.3.3/microsoft-r-open/rpm/microsoft-r-open-mkl-3.3.rpm
      yum:
        name: "{{ packages3_3_3 }}"
        installroot: /cm/images/{{ images_name }}/



    - name: Install R - WISE - 3.4.0
      vars:
        packages3_4_0:
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.0/microsoft-r-open/rpm/microsoft-r-open-mro-3.4.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.0/microsoft-r-open/rpm/microsoft-r-open-foreachiterators-3.4.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.0/microsoft-r-open/rpm/microsoft-r-open-mkl-3.4.rpm
      yum:
        name: "{{ packages3_4_0 }}"
        installroot: /cm/images/{{ images_name }}/



    - name: Install R - WISE - 3.4.1
      vars:
        packages3_4_1:
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.1/microsoft-r-open/rpm/microsoft-r-open-mro-3.4.1.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.1/microsoft-r-open/rpm/microsoft-r-open-foreachiterators-3.4.1.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.1/microsoft-r-open/rpm/microsoft-r-open-mkl-3.4.1.rpm
      yum:
        name: "{{ packages3_4_1 }}"
        installroot: /cm/images/{{ images_name }}/


    - name: Install R - WISE - 3.4.2
      vars:
        packages3_4_2:
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.2/microsoft-r-open/rpm/microsoft-r-open-mro-3.4.2.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.2/microsoft-r-open/rpm/microsoft-r-open-foreachiterators-3.4.2.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.2/microsoft-r-open/rpm/microsoft-r-open-mkl-3.4.2.rpm
      yum:
        name: "{{ packages3_4_2 }}"
        installroot: /cm/images/{{ images_name }}/



    - name: Install R - WISE - 3.4.3
      vars:
        packages3_4_3:
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.3/microsoft-r-open/rpm/microsoft-r-open-mro-3.4.3.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.3/microsoft-r-open/rpm/microsoft-r-open-foreachiterators-3.4.3.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.4.3/microsoft-r-open/rpm/microsoft-r-open-mkl-3.4.3.rpm
      yum:
        name: "{{ packages3_4_3 }}"
        installroot: /cm/images/{{ images_name }}/
  



    - name: Install R - WISE - 3.5.1
      vars:
        packages3_5_1:
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.5.1/microsoft-r-open/rpm/microsoft-r-open-mro-3.5.1.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.5.1/microsoft-r-open/rpm/microsoft-r-open-foreachiterators-3.5.1.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.5.1/microsoft-r-open/rpm/microsoft-r-open-mkl-3.5.1.rpm
      yum:
        name: "{{ packages3_5_1 }}"
        installroot: /cm/images/{{ images_name }}/
  


    - name: Install R - WISE - 3.5.3
      vars:
        packages3_5_3:
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.5.3/microsoft-r-open/rpm/rhel/microsoft-r-open-mro-3.5.3.rpm
          - /Sources/Software/Microsoft/Ropen/src/microsoft-r-open-3.5.3/microsoft-r-open/rpm/rhel/microsoft-r-open-mkl-3.5.3.rpm
      yum:
        name: "{{ packages3_5_3 }}"
        installroot: /cm/images/{{ images_name }}/




