---
- hosts: CM-Tools-Server 
  vars_files:
  - env_variables

  tasks:

    - name: Install R - RSTUDIO - {{ rstudio_version_rpm }}
      vars:
         packagesRstudio:
           - /Sources/Software/rstudio/rstudio-server/{{ rstudio_version_rpm }}.rpm 
      yum:
         name: "{{ packagesRstudio }}"
         installroot: /cm/images/{{ images_name }}/

    - name: Copy file /etc/pam.d/rstudio
      copy:
         src: /cm/shared/apps/UpdateImages/Scenario/R/IDE/src/pam.d/rstudio
         dest: /cm/images/{{ images_name }}/etc/pam.d/rstudio
         backup: yes
         owner: root
         group: root
         mode: '0644'

    - name: RENAME - /cm/images/{{ images_name }}/etc/rstudio
      command: " mv /cm/images/{{ images_name }}/etc/rstudio /cm/images/{{ images_name }}/etc/rstudio.old